language: generic

sudo: required
dist: xenial

script: bash test/test.sh

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y doxygen gcc-arm-none-eabi
  - arm-none-eabi-g++ --version
